name: object_detector
description: "Object detector is no machine"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_pytorch: ^1.0.1
  image_picker: ^0.8.6
  gif: ^2.2.0
  tflite:
    git:
      url: https://github.com/zhengbomo/flutter_tflite.git
      ref: master
  camera: ^0.11.0
  provider: ^5.0.0
  flutter_screenutil: 5.0.0+2
  url_launcher: ^6.0.9
  screenshot:
    git:
      url: https://github.com/Mayb3Nots/screenshot.git
      ref: master
  image_gallery_saver:
    git:
      url: https://github.com/hui-z/image_gallery_saver
      ref: master
  yandex_mapkit: ^4.0.2
  geolocator: ^12.0.0
  arcore_flutter_plugin: ^0.1.0

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/icon.png"
  adaptive_icon_foreground: "assets/images/icon.png"
  adaptive_icon_background: "#ffffff"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/labels/
    - assets/models/yolov2_tiny.txt
    - assets/models/yolov2_tiny.tflite
    - assets/models/ssd_mobilenet.txt
    - assets/models/ssd_mobilenet.tflite
    - assets/models/mobilenet_v1.txt
    - assets/models/mobilenet_v1.tflite
    - assets/models/posenet_mv1_checkpoints.tflite
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat.ttf
          weight: 400

